### ISSUE TITLE
so sorry for unrelated request and issue report

### ISSUE THREAD

**Issue by yonited** [timendum/download-mlol#1]
Hi, I am a big fan of your work and thank you a lot for some amazing Firefox add-ons you already developed.
I was using a great one of them called [aptoide downloader](https://addons.mozilla.org/en-US/firefox/addon/aptoide-downloader/) and it was working perfectly for years, but lately, aptoide updated their website and the addon doesn't work anymore ... can you consider fixing it again, please

Grazie mille

**Comment by timendum** [comment]
Hi, the new aptoide provides a way to download the APK without an addon, there is no need to update "aptoide download".

**Comment by yonited** [comment]
I double-checked and whenever I want to download any game or app, the same file size 23 MB (which is Aptoide APK itself) is what can be generated when you ever try to download any file, also you can't find any way to download games/apps OBB files

**Comment by timendum** [comment]
Thanks for the explanation, I've uploaded a new version on addons mozilla...

**Comment by yonited** [comment]
thank you so much
